# Generated by Django 5.0.6 on 2024-07-04 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarius', '0002_alter_city_options_post_comment_arguments_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arguments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arguments', to='aquarius.comment'),
        ),
        migrations.AlterField(
            model_name='arguments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arguments', to='aquarius.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aquarius.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='aquarius.city'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='aquarius.post'),
        ),
    ]
