# Generated by Django 5.0.6 on 2024-07-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarius', '0003_alter_arguments_comment_alter_arguments_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
