# Generated by Django 5.0.6 on 2024-07-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarius', '0005_report_comment_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='classification',
            field=models.CharField(choices=[('in_favor', 'in_favor'), ('against', 'against'), ('neutral', 'neutral')], default='neutral', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
