# Generated by Django 5.0.6 on 2024-07-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarius', '0006_remove_report_comment_comment_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='HotTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_topics', to='aquarius.city')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_topics', to='aquarius.post')),
            ],
        ),
    ]
